# Generated by Django 4.1.5 on 2023-01-25 22:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=70)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_1_score", models.IntegerField()),
                ("country_2_score", models.IntegerField()),
                (
                    "country_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="country_1", to="mundial.country"
                    ),
                ),
                (
                    "country_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="country_2", to="mundial.country"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Matches",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Goalkeeper", "Goalkeeper"),
                            ("Defender", "Defender"),
                            ("Midfielder", "Midfielder"),
                            ("Striker", "Striker"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="mundial.country"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stadium",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("club", models.CharField(max_length=50, null=True)),
                ("capacity", models.IntegerField()),
                ("field_size", models.IntegerField()),
                ("opening_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "yellow_cards",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                (
                    "red_cards",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("goals", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mundial.match")),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mundial.player")),
            ],
            options={
                "verbose_name_plural": "PlayerMatch",
            },
        ),
        migrations.AddField(
            model_name="match",
            name="stadium",
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="mundial.stadium"),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.CheckConstraint(
                check=models.Q(("position__in", ["Goalkeeper", "Defender", "Midfielder", "Striker"])),
                name="mundial_player_position_valid",
            ),
        ),
    ]
